POST http://localhost:3334/events
Content-Type: application/json

{
  "title": 123,
  "details": "+1 evento de teste",
  "maximumAttendees": 1
}

###

POST http://localhost:3334/events/085c4937-db4d-47b0-b891-ad8a6738698f/attendees
Content-Type: application/json

{
  "name": "Matheus",
  "email": "matheus@gmail.com"
}

###

GET http://localhost:3334/events/085c4937-db4d-47b0-b891-ad8a6738698f

###


GET http://localhost:3334/attendees/10/badge

###

GET http://localhost:3334/attendees/11/check-in

###

GET http://localhost:3334/events/085c4937-db4d-47b0-b891-ad8a6738698f/attendees


