POST http://localhost:3334/events
Content-Type: application/json

{
  "title": "testee",
  "details": "+1 evento de teste",
  "maximumAttendees": 1
}

###

POST http://localhost:3334/events/91aaee89-f992-4fb3-ad4a-3d73752252dd/attendees
Content-Type: application/json

{
  "name": "Matheus",
  "email": "matheus@gmail.com"
}

###

GET http://localhost:3334/events/91aaee89-f992-4fb3-ad4a-3d73752252dd

###


GET http://localhost:3334/attendees/2/badge

###

GET http://localhost:3334/attendees/2/check-in

###

GET http://localhost:3334/events/91aaee89-f992-4fb3-ad4a-3d73752252dd/attendees


